---
#goeko@penguinfish:~/Projects/RaspberryPi/AnsiblePi$ ansible-playbook -i hosts mjpg-streamer.yml -u pi -b -become-method=sudo
- name: Setup MJPG Streamer
  hosts: NewPi

#  vars_prompt:
#    - name: "ssid"
#      prompt: "Please enter your SSID Name:"
#
#  vars:
#    hostname: ssid

## Package Managment
  # install needed packages  Load needed packages
  tasks:
  - name: update package list
    apt:
      update_cache: yes
      cache_valid_time: 3600

#***** need to do this!!!
#  - name: enable camera
# ? copy config script ? 
# could rip config from raspi-config
# enable_camera.sh 

  #$ sudo apt-get install libjpeg8-dev imagemagick libv4l-dev
  - name: install prereqs
    apt:
      name: 
        - cmake
        - libjpeg8-dev
        - libjpeg8-dev
        - imagemagick
        - libv4l-dev
        - git
        - gcc
        - g++

  # https://github.com/jacksonliam/mjpg-streamer
  - name: clone mjpg-streamer
    git:
      repo: 'https://github.com/jacksonliam/mjpg-streamer.git'
      dest: /usr/local/src/

# # https://github.com/jacksonliam/mjpg-streamer
# - name: clone mjpg-streamer
#   ansible.builtin.git:
#     repo: 'https://github.com/jacksonliam/mjpg-streamer.git'
#     dest: /usr/local/src/

  - name: make mjpg-streamer
    make:
      chdir: /usr/local/src/mjpg-streamer-experimental

  - name: make mjpg-streamer install
    make:
      chdir: /usr/local/src/mjpg-streamer-experimental
      target: install

   #$ make mjpg_streamer input_file.so output_http.so
   #$ sudo cp mjpg_streamer /usr/local/bin
   #$ sudo cp output_http.so input_file.so /usr/local/lib/

# - name: test camera working ?
   #$ mkdir /tmp/stream
   #$ raspistill --nopreview -w 640 -h 480 -q 5 -o /tmp/stream/pic.jpg -tl 100 -t 9999999 -th 0:0:0 &

  - name: setup mjpg_streamer www
    file:
      path: /usr/local/www
      state: directory
      mode: "u=rwx,g=rx,o=rx"
      #owner ? 
      # permissions ? 

# **** NOT WORKING ... just says file not found/accessable ? ??????????
#  #$ sudo cp -R www /usr/local/www
# - name: copy mjpg_streamer webfiles
#   copy:
#     src: "/usr/local/src/mjpg-streamer-experimental/www/LICENSE.txt"
#     dest: /tmp

  - name: copy mjpg_streamer webfiles
    command: cp -r /usr/local/src/mjpg-streamer-experimental/www /var

# - name: setup at boot run
# have hack script: start-mjpg_streamer.sh
#
#LD_LIBRARY_PATH=/usr/local/lib mjpg_streamer -i "input_file.so -f /tmp/stream -n pic.jpg" -o "output_http.so -w /usr/local/www"
#  #$ mjpg_streamer -o "output_http.so -w ./www" -i "input_raspicam.so -x 1280 -y 720 -fps 15 -vf"
#
# that may not work ? because of the raspi-config for the camera
#   # check that http://${IP}:8080 responds ? 
#   - debug:
#       msg: mjpg_streamer is available at http://10.1.1.91:8080
# echo "mjpg_streamer should be availabe at ${IP}:8080 shortly (after raspberry reboot)"

#  - name: reboot server
#      command: /sbin/reboot

  handlers:
#      - name: restart hostapd
#            service: name=hostapd state=restarted
